### ISSUE TITLE
An error "packaging.version.InvalidVersion" when open alphaviz on windows 10 

### ISSUE THREAD

**Issue by wuwo007** [MannLabs/alphaviz#40]
I have install the alphaviz by exe file "alphaviz_gui_installer_windows.exe" on my windows 10 computer. When I open the alphaviz, I got the error: "packaging.version.InvalidVersion" , the details is following:
![image](https://github.com/MannLabs/alphaviz/assets/14055402/390058d7-b007-4cca-bd60-525559ee8de3)

Could you help me how to solve this problem?

**Comment by cctsou** [comment]
I encountered the same error message, any help will be appreciated

**Comment by wuwo007** [comment]
I have not solved this problem...

**Comment by ChengkeChou** [comment]
version.InvalidVersion: Invalid version: 'None'
Something went wrong, press any key to continue...
me，too

**Comment by Harry-young-0** [comment]
@wuwo007  any luck yet? I have the same!

Traceback (most recent call last):
  File "alphaviz_pyinstaller.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "alphaviz\gui.py", line 16, in <module>
    import holoviews as hv
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "holoviews\__init__.py", line 11, in <module>
    from . import util                                       # noqa (API import)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "holoviews\util\__init__.py", line 15, in <module>
    from ..core import (
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "holoviews\core\__init__.py", line 3, in <module>
    from .boundingregion import *  # noqa (API import)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "holoviews\core\boundingregion.py", line 12, in <module>
    from .util import datetime_types
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "holoviews\core\util.py", line 53, in <module>
    param_version = LooseVersion(param.__version__)
  File "packaging\version.py", line 200, in __init__
packaging.version.InvalidVersion: Invalid version: 'None'
Something went wrong, press any key to continue...

Is it a python thing - need a fresh install or no local python?
